import { supabaseAdmin } from "../_shared/supabase.ts"
import { logger } from "../_shared/logger.ts"
import { now } from "../_shared/time.ts"
import { geminiJson } from "../_shared/gemini.ts"

interface SeoResult {
  seo_title: string
  seo_description: string
  tags: string[]
}

Deno.serve(async (_req) => {
  let claimedJob: Record<string, unknown> | null = null

  try {
    const { data: job, error: claimError } = await supabaseAdmin.rpc(
      "claim_next_news_job",
      { p_job_type: "ai_seo" },
    )

    if (claimError) throw claimError
    if (!job || !job.id) {
      return new Response(JSON.stringify({ idle: true }), { status: 200 })
    }

    claimedJob = job as Record<string, unknown>
    const articleId = (job as any).article_id || (job as any).payload?.article_id
    if (!articleId) throw new Error("No article_id in job")

    const { data: article, error: fetchError } = await supabaseAdmin
      .from("news_articles")
      .select("id, title, content, language")
      .eq("id", articleId)
      .is("deleted_at", null)
      .single()

    if (fetchError) throw fetchError
    if (!article) throw new Error(`Article ${articleId} not found`)

    const plainContent = (article.content ?? "").replace(/<[^>]*>/g, "").trim()

    let result: SeoResult
    try {
      result = await geminiJson<SeoResult>(
        `You are an SEO expert for agricultural news. Generate optimized SEO metadata.

Article title: ${article.title}
Article content: ${plainContent.substring(0, 2000)}

Generate:
1. SEO title (max 60 chars, include main keyword)
2. SEO description (max 160 chars, compelling summary)
3. 5-10 relevant tags for agricultural news

Return JSON only:
{"seo_title": "...", "seo_description": "...", "tags": ["tag1", "tag2", ...]}`,
        { temperature: 0.5, maxTokens: 512 },
      )
    } catch (aiErr) {
      logger.warn(`Gemini SEO failed, using fallback: ${(aiErr as Error).message}`)
      const words = plainContent.split(/\s+/).filter(Boolean)
      result = {
        seo_title: (article.title ?? "").substring(0, 60),
        seo_description: words.length > 30 ? words.slice(0, 30).join(" ") + "..." : plainContent.substring(0, 160),
        tags: words.slice(0, 10).map((w: string) => w.replace(/[^a-zA-Z0-9а-яёўғҳ]/g, "").toLowerCase()).filter(Boolean),
      }
    }

    const { error: updateError } = await supabaseAdmin
      .from("news_articles")
      .update({
        ai_seo_title: result.seo_title,
        ai_seo_description: result.seo_description,
        ai_tags: result.tags,
        seo_title: result.seo_title,
        seo_description: result.seo_description,
      })
      .eq("id", articleId)

    if (updateError) throw updateError

    await supabaseAdmin.rpc("enqueue_news_job", {
      p_job_type: "draft_generate",
      p_payload: { article_id: articleId },
      p_priority: 0,
      p_article_id: articleId,
    })

    await supabaseAdmin.from("news_jobs").update({
      status: "completed",
      completed_at: now(),
      result: { tags_count: result.tags.length },
    }).eq("id", (job as any).id)

    await supabaseAdmin.rpc("log_ingestion", {
      p_job_id: (job as any).id,
      p_source_id: (job as any).source_id,
      p_event_type: "ai_processed",
      p_message: "SEO metadata generated by Gemini AI",
      p_metadata: { article_id: articleId, tags: result.tags },
    })

    logger.info(`ai_seo completed for article ${articleId}`, {
      metadata: { job_id: (job as any).id, tags: result.tags },
    })

    return new Response(JSON.stringify({
      success: true,
      article_id: articleId,
      tags: result.tags,
    }), { status: 200 })
  } catch (err) {
    const error = err as Error
    logger.error(`ai_seo worker failed: ${error.message}`, { metadata: { error: error.stack } })

    if (claimedJob) {
      await supabaseAdmin.from("news_jobs").update({
        status: "failed",
        error_message: error.message,
        completed_at: now(),
      }).eq("id", claimedJob.id)
      await supabaseAdmin.rpc("log_ingestion", {
        p_job_id: claimedJob.id,
        p_source_id: (claimedJob as any).source_id,
        p_event_type: "failed",
        p_message: error.message,
        p_metadata: { error: error.stack },
      })
    }

    return new Response(JSON.stringify({ error: error.message }), { status: 500 })
  }
})
